// Generated by Wrangler (manually from wrangler types output)
/// <reference types="@cloudflare/workers-types" />
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_DATABASE_ID: string;
		CLOUDFLARE_D1_TOKEN: string;
	}
}
interface Env extends Cloudflare.Env {}
